### ISSUE TITLE
cache with restore-keys

### ISSUE THREAD

**Issue by steshaw** [kowainik/.github#14]
Hi, it looks like your template workflow could benefit from `restore-keys` in the cache action.

I recently discovered this myself [in this example project](https://github.com/steshaw/summon-haskell-example/blob/master/.github/workflows/ci.yml) which started out as a scaffold created with Summoner (master branch).

It'd be something like:

```yaml
    - uses: actions/cache@v2.1.3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key:
          ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          ${{ runner.os }}-${{ matrix.ghc }}-
```

It would probably also be good to cache `dist-newstyle` for Cabal builds and `.stack-work` for Stack builds. In my example project above, I used a single cache but it could be better to use a separate cache for `~/.cabal/store` and `dist-newstyle`  (similarly for Stack).

I'm happy to put together a PR if this seems reasonable. I suppose these changes could be folded into Summoner also if you are happy with that.
